core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('login/', views.login_page, name='login'),
    path('logout/', views.logout_page, name='logout'),
    path('signin/', views.signin_page, name='signin'),
    path('room/<str:pk>/', views.room, name='room'),
    path('create-room/', views.create_room, name='create-room'),
    path('update-room/<str:pk>/', views.update_room, name='update-room'),
    path('delete-room/<str:pk>/', views.delete_room, name='delete-room'),
    path('delete-message/<str:pk>/', views.delete_message, name='delete-message'),
    path('edit-user/', views.edit_user, name='edit-user'),
    path('profile/<str:pk>/', views.user_profile, name='user-profile'),
    path('topics/', views.topics_page, name='topics'),
    path('activity/', views.activity_page, name='activity'),



]

studybud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('api/', include('core.api.urls'))
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=150)
    description = models.TextField(max_length=500, blank=True, null=True)
    participants = models.ManyToManyField(User, related_name='participants', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.name


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField(max_length=500)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-updated', '-created']

    def __str__(self):
        return self.body[0:50]

templates/activity.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% endblock title %}

{% block content %}

    <main class="layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                                ></path>
                            </svg>
                        </a>
                        <h3>Recent Activities</h3>
                    </div>
                </div>
                {% for room in rooms %}
                    <div class="activities-page layout__body">
                        <div class="activities__box">
                            <div class="activities__boxHeader roomListRoom__header">
                                <a href="../theme/profile.html" class="roomListRoom__author">
                                    <div class="avatar avatar--small">
                                        <img src="https://randomuser.me/api/portraits/women/11.jpg"/>
                                    </div>
                                    <p>
                                        @{{ room.host }}
                                        <span>{{ room.created|timesince }} ago</span>
                                    </p>
                                </a>

                                {% if request.user == room.host %}
                                    <div class="roomListRoom__actions">
                                        <a href="{% url 'delete-room' room.id %}">
                                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                                 viewBox="0 0 32 32">
                                                <title>remove</title>
                                                <path
                                                        d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
                                                ></path>
                                            </svg>
                                        </a>
                                    </div>
                                {% endif %}
                            </div>
                            <div class="activities__boxContent">
                                <p>replied to post “<a href="../theme/room.html">{{ room.name }}</a>”</p>
                                <div class="activities__boxRoomContent">
                                    {{ room.description }}                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </main>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

templates/activity_component.html
<div class="activities">
	<div class="activities__header">
		<h2>Recent Activities</h2>
	</div>

	{% for message in room_messages %}
		<div class="activities__box">
			<div class="activities__boxHeader roomListRoom__header">
				<a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
					<div class="avatar avatar--small">
						<img src="https://randomuser.me/api/portraits/women/11.jpg" alt=""/>
					</div>
					<p>
						@{{ message.user }}
						<span>{{ message.created|timesince }}</span>
					</p>
				</a>
				{% if user == message.user %}
					<div class="roomListRoom__actions">
						<a href="{% url 'delete-message' message.id %}">
							<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
							     viewBox="0 0 32 32">
								<title>remove</title>
								<path
										d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z"
								></path>
							</svg>
						</a>
					</div>
				{% endif %}
			</div>
			<div class="activities__boxContent">
				<p>replied to post <a href="{% url 'room' message.room.id %}">“{{ message.room.name }}</a>”</p>
				<div class="activities__boxRoomContent">
					{{ message }}
				</div>
			</div>
		</div>
	{% endfor %}
</div>

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link
            rel="shortcut icon"
            href="{% static 'assets/favicon.ico' %}"
            type="image/x-icon"
    />
    <link rel="stylesheet" href="{% static '/css/style.css' %}"/>
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
{% include 'navbar.html' %}

<div class="container">
    {% if messages %} {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {{ message }}
        </li>
    {% endfor %} {% endif %}
    {% block content %}

    {% endblock content %}
</div>

<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {% endblock title %}

{% block content %}

    <main class="delete-item layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{{ request.META.HTTP_REFERER }}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Back</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="form__group">
                            <p>Are you sure you want to delete "{{ obj }}"?</p>
                        </div>

                        <div class="for__group">
                            <input class="btn btn--main" type="submit" value="Confirm"/>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </main>
    <script src="{% static 'js/script.js' %}"></script>
{% endblock content %}

templates/edit-user.html
{% extends 'base.html' %}
{% load static %}

{% block title %} {% endblock title %}

{% block content %}
    <main class="update-account layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Edit your profile</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form method="POST" action="">
                        {% csrf_token %}



                        {% for field in form %}
                            <div class="form__group">
                                <label for="profile_pic">{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}


                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'home' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>
{% endblock content %}

templates/feed_component.html
	{% for room in rooms %}
		<div class="roomListRoom">
			<div class="roomListRoom__header">
				<a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
					<div class="avatar avatar--small active">
						<img src="https://randomuser.me/api/portraits/men/11.jpg" alt=""/>
					</div>
					<span>@{{ room.host.username }}</span>
				</a>
				<div class="roomListRoom__actions">
					<span>{{ room.created|timesince }}</span>
				</div>
			</div>
			<div class="roomListRoom__content">
				<a href="{% url 'room' room.id %}">{{ room.name }}</a>

			</div>
			<div class="roomListRoom__meta">
				<a class="roomListRoom__joined">
					<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
						<title>user-group</title>
						<path
								d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
						></path>
						<path
								d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
						></path>
						<path
								d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
						></path>
						<path
								d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
						></path>
					</svg>
					{{ room.participants.all.count }} Joined
				</a>
				<p class="roomListRoom__topic">{{ room.topic }}</p>
			</div>
		</div>
	{% endfor %}



templates/home.html
{% extends 'base.html' %}

{% block title %} {% endblock title %}

{% block content %}
    <main class="layout layout--3">
        <!-- Topics Start -->
        <div class="container">
            {% include 'topic_component.html' %}

            <!-- Topics End -->

            <!-- Room List Start -->
            <div class="roomList">
                <div class="mobile-menu">
                    <form action="{% url 'home' %}" class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input name="q" placeholder="Search for posts"/>
                        </label>
                    </form>
                    <div class="mobile-menuItems">
                        <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
                        <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
                    </div>
                </div>
                <div class="roomList__header">
                    <div>
                        <h2>Study Room</h2>
                        <p>{{ room_count }} Rooms available</p>
                    </div>
                    <a class="btn btn--main" href="{% url 'create-room' %}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <title>add</title>
                            <path
                                    d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
                            ></path>
                        </svg>
                        Create Room
                    </a>
                </div>
                {% include 'feed_component.html' %}
            </div>
            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'activity_component.html' %}
            <!-- Activities End -->
        </div>
    </main>
{% endblock content %}

templates/login_register.html
{% extends 'base.html' %}

{% block title %}


{% endblock title %}

{% block content %}
    {% if page == 'login' %}
        <main class="auth layout">
            <div class="container">
                <div class="layout__box">
                    <div class="layout__boxHeader">
                        <div class="layout__boxTitle">
                            <h3>Login</h3>
                        </div>
                    </div>
                    <div class="layout__body">
                        <h2 class="auth__tagline">Find your study partner</h2>

                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="form__group form__group">
                                <label for="username">Username</label>
                                <input id="username" name="username" type="text" placeholder="e.g. dennis_ivy"/>
                            </div>
                            <div class="form__group">
                                <label for="password">Password</label>
                                <input
                                        id="password"
                                        name="password"
                                        type="password"
                                        placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;"
                                />
                            </div>

                            <button class="btn btn--main" type="submit">
                                <svg
                                        version="1.1"
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="32"
                                        height="32"
                                        viewBox="0 0 32 32"
                                >
                                    <title>lock</title>
                                    <path
                                            d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z"
                                    ></path>
                                    <path
                                            d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z"
                                    ></path>
                                </svg>

                                Login
                            </button>
                        </form>

                        <div class="auth__action">
                            <p>Haven't signed up yet?</p>
                            <a href="{% url 'signin' %}" class="btn btn--link">Sign Up</a>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    {% elif page == 'signup' %}

        <main class="auth layout">
            <div class="container">
                <div class="layout__box">
                    <div class="layout__boxHeader">
                        <div class="layout__boxTitle">
                            <h3>Sign up</h3>
                        </div>
                    </div>
                    <div class="layout__body">
                        <h2 class="auth__tagline">Find your study partner</h2>

                        <form method="POST" action="">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form__group form__group">
                                    <label for="firstname">{{ field.label }}</label>
                                    {{ field }}
                                </div>
                            {% endfor %}
                        </form>

                        <div class="auth__action">
                            <p>Already have an account?</p>
                            <a href="{% url 'login' %}" class="btn btn--link">Log In</a>
                        </div>
                    </div>
                </div>
            </div>
        </main>



    {% endif %}

{% endblock content %}

templates/navbar.html
{% load static %}

<header class="header header--loggedIn">
    <div class="container">
        <a href="/" class="header__logo">
            <img src="{% static 'assets/logo.svg' %}" alt=""/>
            <h1>StudyBuddy</h1>
        </a>

        <form class="header__search" method="GET" action="{% url 'home' %}">
            <label>
                <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                </svg>
                <input name="q" placeholder="Search for rooms..."/>
            </label>
        </form>

        <nav class="header__menu">
            {% if user.is_authenticated %}
                <!-- Logged In -->
                <div class="header__user">
                    <a href="{% url 'edit-user' %}">
                        <div class="avatar avatar--medium active">
                            <img src="https://randomuser.me/api/portraits/men/37.jpg" alt=""/>
                        </div>
                        <p>John Doe <span>@{{ user.username }}</span></p>
                    </a>
                    <button class="dropdown-button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                             viewBox="0 0 32 32">
                            <title>chevron-down</title>
                            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
                        </svg>
                    </button>
                </div>

            {% else %}
                <a href="{% url 'login' %}">
                    <img src="{% static 'assets/avatar.svg' %}" alt=""/>
                    <p>Login</p>
                </a>

            {% endif %}

            <div class="dropdown-menu">
                <a href="{% url 'edit-user' %}" class="dropdown-link"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                         viewBox="0 0 32 32">
                    </svg>
                    Settings</a>

                <a href="{% url 'logout' %}" class="dropdown-link">
                    <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                         viewBox="0 0 32 32">
                    </svg>
                    Logout</a>
            </div>
        </nav>
    </div>
</header>


templates/profile.html
{% extends 'base.html' %} {% block title %}
{% endblock title %}

{% block content %}
    <main class="profile-page layout layout--3">
        <div class="container">
            <!-- Topics Start -->
            {% include 'topic_component.html' %}
            <!-- Topics End -->

            <!-- Room List Start -->

            <div class="roomList">
                <div class="profile">
                    <div class="profile__avatar">
                        <div class="avatar avatar--large active">
                            <img src="https://randomuser.me/api/portraits/men/11.jpg" alt=""/>
                        </div>
                    </div>
                    <div class="profile__info">
                        <h3>Dennis Kardasian Ivy</h3>
                        <p>@{{ user.username }}</p>
                        {% if request.user == user %}
                            <a href="{% url 'edit-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
                        {% endif %}
                    </div>
                    <div class="profile__about">
                        <h3>Bio</h3>
                        <p>
                            Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur illo tenetur
                            facilis sunt nemo debitis quisquam hic atque aut? Ducimus alias placeat optio
                            accusamus repudiandae quis ab ex exercitationem rem?
                        </p>
                    </div>
                </div>
                <div>
                    <h2>Study Rooms Hosted by {{ user }}
                    </h2>
                </div>
                {% include 'feed_component.html' %}
            </div>

            <!-- Room List End -->

            <!-- Activities Start -->
            {% include 'activity_component.html' %}
            <!-- Activities End -->
        </div>
    </main>

{% endblock content %}

templates/room_form.html
{% extends 'base.html' %}
{% block title %} {% endblock title %}

{% block content %}
    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                                </path>
                            </svg>
                        </a>
                        <h3>Create/Edit Study Room</h3>
                    </div>
                </div>
                <div class="layout__body">
                    <form method="POST">
                        {% csrf_token %}

                        <div class="form__group">
                            <label for="room_name">Room Topic</label>
                            {{ form.topic }}
                        </div>

                        <div class="form__group">
                            <label for="room_name">Room Name</label>
                            {{ form.name }}
                        </div>

                        <div class="form__group">
                            <label for="room_name">Room Description</label>
                            {{ form.description }}
                        </div>


                        <div class="form__action">
                            <a class="btn btn--dark" href="{% url 'create-room' %}">Cancel</a>
                            <button class="btn btn--main" type="submit">Create Room</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </main>

{% endblock content %}

templates/topic_component.html
<div class="topics">
	<div class="topics__header">
		<h2>Browse Topics</h2>
	</div>
	<ul class="topics__list">
		<li>
			<a href="{% url 'home' %}" class="active">All <span>{{ topics.count }}</span></a>
		</li>
		{% for topic in topics %}
			<li>
				<a href="{% url 'home' %}?q={{ topic.name }} " class="active">{{ topic.name }}
					<span>{{ topic.room_set.all.count }}</span></a>
			</li>
		{% endfor %}
	</ul>
	<a class="btn btn--link" href="{% url 'topics' %}">
		More
		<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
			<title>chevron-down</title>
			<path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
		</svg>
	</a>
</div>

templates/topics.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main class="create-room layout">
        <div class="container">
            <div class="layout__box">
                <div class="layout__boxHeader">
                    <div class="layout__boxTitle">
                        <a href="{% url 'home' %}">
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>arrow-left</title>
                                <path
                                        d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z"
                                ></path>
                            </svg>
                        </a>
                        <h3>Browse Topics</h3>
                    </div>
                </div>

                <div class="topics-page layout__body">
                    <form action="" method="GET" class="header__search">
                        <label>
                            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                                 viewBox="0 0 32 32">
                                <title>search</title>
                                <path
                                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
                                ></path>
                            </svg>
                            <input name="q" placeholder="Search for topics"/>
                        </label>
                    </form>

                    <ul class="topics__list">
                        <li>
                            <a href="{% url 'topics' %}" class="active">All <span>{{ topics.count }}</span></a>
                        </li>
                        {% for topic in topics %}
                            <li>
                                <a href="{% url 'home' %}?q={{ topic.name }}">{{ topic.name }}
                                    <span>{{ topic.room_set.all.count }}</span></a>
                            </li>
                        {% endfor %}

                    </ul>
                </div>
            </div>
        </div>
    </main>

    <script src="{% static 'js/script.js' %}"></script>
{% endblock content %}